apiVersion: v1
kind: Service
metadata:
  name: redisinsight-network-service
  namespace: star-bank-devops-tools
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 32004
  selector:
    app: redisinsight