kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
  namespace: star-bank-ns
spec:
  replicas: 2
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: '0'
        - name: KAFKA_ADVERTISED_PORT
          value: '31865'
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.59.102
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://192.168.59.102:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 192.168.59.102:30098