apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-network-service
  namespace: star-bank-ns
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    nodePort: 32201
    targetPort: 9092
  selector:
    app: kafka-broker