apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-network-service
  namespace: star-bank-ns
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 32204
      targetPort: 2181
  selector:
    app: zookeeper