apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: star-bank-ns
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: test123