apiVersion: v1
kind: Service
metadata:
  name: postgres-network-service
  namespace: star-bank-ns
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '5432'
spec:
  selector:
    app: postgres-deployment
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32202