apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pgadmin-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-persistent-volume
  labels:
    type: local
spec:
  storageClassName: pgadmin-local-storage
  claimRef:
    name: pgadmin-persistent-volume-claim
    namespace: star-bank-devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pgadmin-pv/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-persistent-volume-claim
  namespace: star-bank-devops-tools
spec:
  storageClassName: pgadmin-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

