apiVersion: v1
kind: Service
metadata:
  name: pgadmin-network-service
  namespace: star-bank-devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '80'
spec:
  selector:
    app: pgadmin-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32101